bury_func_case_1 = {'argcount': 2,
                    'cellvars': (),
                    'code': '7c007c0117005300',
                    'consts': [(None, 'NoneType')],
                    'filename': 'filename',
                    'firstlineno': '0',
                    'flags': 67,
                    'freevars': (),
                    'globals': {},
                    'kwonlyargcount': 0,
                    'lnotab': '0001',
                    'name': 'dummy_func_1',
                    'names': (),
                    'nlocals': 2,
                    'object_type': 'function',
                    'posonlyargcount': 0,
                    'stacksize': 2,
                    'type_globals': {},
                    'varnames': ('var1', 'var2')}

bury_func_case_2 = {'argcount': 2,
                    'cellvars': (),
                    'code': '7c007c01170074006a011700740217005300',
                    'consts': [(None, 'NoneType')],
                    'filename': 'filename',
                    'firstlineno': '0',
                    'flags': 67,
                    'freevars': (),
                    'globals': {'G': 10, 'math': 'math'},
                    'kwonlyargcount': 0,
                    'lnotab': '0001',
                    'name': 'dummy_func_2',
                    'names': ('math', 'pi', 'G'),
                    'nlocals': 2,
                    'object_type': 'function',
                    'posonlyargcount': 0,
                    'stacksize': 2,
                    'type_globals': {'G': 'int', 'math': 'module'},
                    'varnames': ('var1', 'var2')}

bury_class_case_1 = {'bases': {},
                     'fields': {},
                     'methods': {'__init__': {'argcount': 1,
                                              'cellvars': (),
                                              'code': '740064018301010064005300',
                                              'consts': [(None, 'NoneType'), ('Awake!', 'str')],
                                              'filename': 'filename',
                                              'firstlineno': '0',
                                              'flags': 67,
                                              'freevars': (),
                                              'globals': {},
                                              'kwonlyargcount': 0,
                                              'lnotab': '0001',
                                              'name': '__init__',
                                              'names': ('print',),
                                              'nlocals': 1,
                                              'object_type': 'function',
                                              'posonlyargcount': 0,
                                              'stacksize': 2,
                                              'type_globals': {},
                                              'varnames': ('self',)},
                                 'greetings': {'argcount': 1,
                                               'cellvars': (),
                                               'code': '64015300',
                                               'consts': [(None, 'NoneType'), (True, 'bool')],
                                               'filename': 'filename',
                                               'firstlineno': '0',
                                               'flags': 67,
                                               'freevars': (),
                                               'globals': {},
                                               'kwonlyargcount': 0,
                                               'lnotab': '0001',
                                               'name': 'greetings',
                                               'names': (),
                                               'nlocals': 1,
                                               'object_type': 'function',
                                               'posonlyargcount': 0,
                                               'stacksize': 1,
                                               'type_globals': {},
                                               'varnames': ('self',)}},
                     'object_type': 'class'}

bury_class_case_2 = {'bases': {},
                     'fields': {},
                     'methods': {'__init__': {'argcount': 3,
                                              'cellvars': (),
                                              'code': '7c017c005f007c027c005f0164005300',                          'consts': [(None, 'NoneType')],
                                              'filename': 'filename',
                                              'firstlineno': '0',
                                              'flags': 67,
                                              'freevars': (),
                                              'globals': {},
                                              'kwonlyargcount': 0,
                                              'lnotab': '00010601',
                                              'name': '__init__',
                                              'names': ('a', 'b'),
                                              'nlocals': 3,
                                              'object_type': 'function',
                                              'posonlyargcount': 0,
                                              'stacksize': 2,
                                              'type_globals': {},
                                              'varnames': ('self', 'a', 'b')},
                                 'greetings_imroved': {'argcount': 2,
                                                       'cellvars': (),
                                                       'code': '7c006a007c006a0117007c0117005300',
                                                       'consts': [(None, 'NoneType')],
                                                       'filename': 'filename',
                                                       'firstlineno': '0',
                                                       'flags': 67,
                                                       'freevars': (),
                                                       'globals': {},
                                                       'kwonlyargcount': 0,
                                                       'lnotab': '0001',
                                                       'name': 'greetings_imroved',
                                                       'names': ('a', 'b'),
                                                       'nlocals': 2,
                                                       'object_type': 'function',
                                                       'posonlyargcount': 0,
                                                       'stacksize': 2,
                                                       'type_globals': {},
                                                       'varnames': ('self', 'a')}},
                     'object_type': 'class'}

bury_object_case_1 = {'classes': {},
                      'fields': {'dummy_arg': ('dummy', 'str')},
                      'functions': {},
                      'methods': {'__init__': {'argcount': 1,
                                               'cellvars': (),
                                               'code': '740064018301010064005300',
                                               'consts': [(None, 'NoneType'), ('Awake!', 'str')],
                                               'filename': 'filename',
                                               'firstlineno': '0',
                                               'flags': 67,
                                               'freevars': (),
                                               'globals': {},
                                               'kwonlyargcount': 0,
                                               'lnotab': '0001',
                                               'name': '__init__',
                                               'names': ('print',),
                                               'nlocals': 1,
                                               'object_type': 'function',
                                               'posonlyargcount': 0,
                                               'stacksize': 2,
                                               'type_globals': {},
                                               'varnames': ('self',)},
                                  'greetings': {'argcount': 1,
                                                'cellvars': (),
                                                'code': '64015300',
                                                'consts': [(None, 'NoneType'), (True, 'bool')],
                                                'filename': 'filename',
                                                'firstlineno': '0',
                                                'flags': 67,
                                                'freevars': (),
                                                'globals': {},
                                                'kwonlyargcount': 0,
                                                'lnotab': '0001',
                                                'name': 'greetings',
                                                'names': (),
                                                'nlocals': 1,
                                                'object_type': 'function',
                                                'posonlyargcount': 0,
                                                'stacksize': 1,
                                                'type_globals': {},
                                                'varnames': ('self',)}},
                      'object_type': 'object',
                      'objects': {}}

bury_object_case_2 = {'classes': {},
                      'fields': {'a': (1, 'int'), 'b': (2, 'int')},
                      'functions': {'dummy_arg': {'argcount': 2,
                                                  'cellvars': (),
                                                  'code': '7c007c01170074006a011700740217005300',
                                                  'consts': [(None, 'NoneType')],
                                                  'filename': 'filename',
                                                  'firstlineno': '0',
                                                  'flags': 67,
                                                  'freevars': (),
                                                  'globals': {'G': 10, 'math': 'math'},
                                                  'kwonlyargcount': 0,
                                                  'lnotab': '0001',
                                                  'name': 'dummy_func_2',
                                                  'names': ('math', 'pi', 'G'),
                                                  'nlocals': 2,
                                                  'object_type': 'function',
                                                  'posonlyargcount': 0,
                                                  'stacksize': 2,
                                                  'type_globals': {'G': 'int', 'math': 'module'},
                                                  'varnames': ('var1', 'var2')}},
                      'methods': {'__init__': {'argcount': 3,
                                               'cellvars': (),
                                               'code': '7c017c005f007c027c005f0164005300',                          'consts': [(None, 'NoneType')],
                                               'filename': 'filename',
                                               'firstlineno': '0',
                                               'flags': 67,
                                               'freevars': (),
                                               'globals': {},
                                               'kwonlyargcount': 0,
                                               'lnotab': '00010601',
                                               'name': '__init__',
                                               'names': ('a', 'b'),
                                               'nlocals': 3,
                                               'object_type': 'function',
                                               'posonlyargcount': 0,
                                               'stacksize': 2,
                                               'type_globals': {},
                                               'varnames': ('self', 'a', 'b')},
                                  'greetings_imroved': {'argcount': 2,
                                                        'cellvars': (),
                                                        'code': '7c006a007c006a0117007c0117005300',
                                                        'consts': [(None, 'NoneType')],
                                                        'filename': 'filename',
                                                        'firstlineno': '0',
                                                        'flags': 67,
                                                        'freevars': (),
                                                        'globals': {},
                                                        'kwonlyargcount': 0,
                                                        'lnotab': '0001',
                                                        'name': 'greetings_imroved',
                                                        'names': ('a', 'b'),
                                                        'nlocals': 2,
                                                        'object_type': 'function',
                                                        'posonlyargcount': 0,
                                                        'stacksize': 2,
                                                        'type_globals': {},
                                                        'varnames': ('self', 'a')}},
                      'object_type': 'object',
                      'objects': {}}
